### ISSUE TITLE
Crashing iOS 10.0.2 / iPhone 7

### ISSUE THREAD

**Issue by Damien514** [EddyVerbruggen/cordova-plugin-taptic-engine#2]
Hello,

I can’t have the plugin to work. It crash all the time when I invoke:

if (window.TapticEngine) TapticEngine.selection();

Crashed happen in main.m "int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate");"

Tell me how I can help you with more information to debug the plugin!

Thanks a lot.

Damien

**Comment by mlynch** [comment]
Can confirm over here. Going to see if I can't fix it and send a PR over

**Comment by EddyVerbruggen** [comment]
Thanks for confirming this. If you can't find it let me know what you did to (re)produce this issue and I'll take a look. But appreciate that you'll try to fix it!

**Comment by mlynch** [comment]
@EddyVerbruggen thanks. Debugging right now, here's the output when it crashes:

<img width="419" alt="screenshot 2016-10-05 15 16 37" src="https://cloud.githubusercontent.com/assets/11214/19129918/c5f47698-8b0e-11e6-8568-6f114c5f7961.png">

Appears related to the `runInBackground`, seems Feedback has to be on the main thread.

**Comment by mlynch** [comment]
Can confirm removing the `runInBackground` fixes. Shall I send a PR for this and the other ones?

**Comment by EddyVerbruggen** [comment]
Yes please!

Does it crash every single time? It's so weird I didn't see that. Granted, I added the background stuff later because Cordova was screaming at me in the log that it was better to use a background thread, but it's hardly justifiable since it's a very quick operation anyway.

I'll refer future folks complaining about those log statements to this issue :)

TIA for the PR! 👍

**Comment by Damien514** [comment]
Thank you for the fix 👍

**Comment by EddyVerbruggen** [comment]
@Damien514 And thank you for reporting this as well, I just hadn't found the time yet to dive into this.

**Comment by mlynch** [comment]
Cool, PR submitted #3. Thanks for this plugin Eddy!

**Comment by EddyVerbruggen** [comment]
Now available on npm (2.0.1) - now go create something awesome!
