### ISSUE TITLE
Plugin 'TapticEngine' not found or is not a CDVPlugin

### ISSUE THREAD

**Issue by brittonk** [EddyVerbruggen/cordova-plugin-taptic-engine#5]
Plugin is returning not found error and not working.

Building with Xcode Version 10.1

The plugin .m and .h files are found in the plugin folder within the build and the entry is being made in config.xml so not sure why it is erroring as not found. Any ideas?

**Comment by willmero** [comment]
I also had this issue, and resolved by following your suggestion above @brittonk ! Thanks!

**Comment by alekseykarpenko** [comment]
If anyone like me will fault with tryings to make this plugin work with Ionic4 & Capacitor:

**DO NOT USE THIS PLUGIN!**

For Ionic4 there is a native Capacitor alternative:
https://capacitor.ionicframework.com/docs/apis/haptics
